OPENAI_API_KEY = "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"

EMAIL_ADDRESS = "jesselakra123@gmail.com"
EMAIL_PASSWORD = "cxahjaovvzhvojrj"